#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: 
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DB: sendmaildb

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <YOUR EMAIL ADDRESS>
EMAIL_PASSWORD: <YOUR APP PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}